(use-modules (gnu packages avr)
             (gnu packages cross-base)
             (gnu packages embedded)
             (gnu packages firmware)
             (gnu packages flashing-tools)
             (gnu packages textutils))
(packages->manifest (list (make-arm-none-eabi-nano-toolchain-12.3.rel1)
                          (make-avr-toolchain)
                          dfu-util qmk dos2unix))
